package com.ts.messenger.entities;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="messenger_guest_room")
public class GuestRoomEntity {

	@Id
	@Column(name="id")
	private int id;
	
	@Column(name="guest_username")
	private String guestUsername;
	
	@Column(name="email")
	private String email;
	
	@Column(name="room_number")
	private String roomNumber;
	
	@Column(name="room_type_code")
	private String roomTypeCode;
	
	@Column(name="logged_out")
	private Date loggedOut;
	
	@Column(name="date")
	private Date date;
	
	@Column(name="hotel_username")
	private String hotelUsername;
	
	@Column(name="hotel_id")
	private String hotelId;
	
	@Column(name="last_content_time")
	private String lastContentTime;
	
	/* Generated by guest user name and room number*/
	@Column(name="security_token")
	private String securityToken;
	
	public GuestRoomEntity() {}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getRoomTypeCode() {
		return roomTypeCode;
	}

	public void setRoomTypeCode(String roomTypeCode) {
		this.roomTypeCode = roomTypeCode;
	}

	public String getRoomNumber() {
		return roomNumber;
	}

	public void setRoomNumber(String roomNumber) {
		this.roomNumber = roomNumber;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getGuestUsername() {
		return guestUsername;
	}

	public void setGuestUsername(String guestUsername) {
		this.guestUsername = guestUsername;
	}

	public String getHotelUsername() {
		return hotelUsername;
	}

	public void setHotelUsername(String hotelUsername) {
		this.hotelUsername = hotelUsername;
	}

	public String gethotelId() {
		return hotelId;
	}

	public void sethotelId(String hotelId) {
		this.hotelId = hotelId;
	}

	public String getLastContentTime() {
		return lastContentTime;
	}

	public void setLastContentTime(String lastContentTime) {
		this.lastContentTime = lastContentTime;
	}

	public String getSecurityToken() {
		return securityToken;
	}

	public void setSecurityToken(String securityToken) {
		this.securityToken = securityToken;
	}

	public Date getLoggedOut() {
		return loggedOut;
	}

	public void setLoggedOut(Date loggedOut) {
		this.loggedOut = loggedOut;
	}
}