
CREATE TABLE `messenger_guest_room` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `guest_username` varchar(500) NOT NULL,
  `email` varchar(500) NOT NULL,
  `room_number` varchar(500) DEFAULT NULL,
  `room_type_code` varchar(32) DEFAULT NULL,
  `logged_out` date DEFAULT NULL,
  `date` datetime DEFAULT CURRENT_TIMESTAMP,
  `hotel_username` varchar(32) DEFAULT NULL,
  `hotel_id` bigint(20) DEFAULT NULL,
  `last_content_time` varchar(45) DEFAULT NULL,
  `security_token` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=latin1 COMMENT='TS: Created for messenger service, saves chat details with a security token generated by chat details for each guest_room';
 
 
CREATE TABLE `messenger_message` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sender` varchar(500) DEFAULT NULL,
  `receiver` varchar(500) DEFAULT NULL,
  `content` longtext,
  `content_type` varchar(200) DEFAULT NULL,
  `guest_room_id` int(11) DEFAULT NULL,
  `status` varchar(300) DEFAULT NULL,
  `room_number` varchar(500) DEFAULT NULL,
  `reservation_number` varchar(450) DEFAULT NULL,
  `created_date` datetime DEFAULT CURRENT_TIMESTAMP
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=255 DEFAULT CHARSET=latin1 COMMENT='TS: Created for messenger service, saves chat messages linked to messenger_guest_room table';


-- TRIGGERS
-- Update last message time after insert new message in messenger_message table
-- Delete logged_out guest rooms more then 6 months from messenger_guest_room after insert new message in messenger_message table
CREATE TRIGGER `messenger_message_AFTER_INSERT` AFTER INSERT ON `messenger_message` FOR EACH ROW
BEGIN
 UPDATE messenger_guest_room SET last_content_time = date_format(NEW.created_date, '%H:%i') WHERE id = NEW.guest_room_id;
 DELETE FROM messenger_guest_room WHERE logged_out IS NOT NULL AND DATE_ADD(DATE(logged_out), INTERVAL 6 MONTH) < DATE(NOW());
END

-- Delete messages from messenger_message after updating logged_out date in messenger_guest_room table
CREATE TRIGGER `messenger_guest_room_AFTER_INSERT` AFTER INSERT ON `messenger_guest_room` FOR EACH ROW
BEGIN
  DECLARE done INT DEFAULT FALSE;
  DECLARE selectLoggedOutGuestsId int; 
  DECLARE selectLoggedOutGuests CURSOR FOR SELECT id FROM messenger_guest_room WHERE logged_out IS NOT NULL AND DATE_ADD(DATE(logged_out), INTERVAL 6 MONTH) < DATE(NOW());
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
  
  OPEN selectLoggedOutGuests;
  read_loop: LOOP
    FETCH selectLoggedOutGuests INTO selectLoggedOutGuestsId;
    IF done THEN
      LEAVE read_loop;
    END IF;
    DELETE FROM messenger_message WHERE guest_room_id = selectLoggedOutGuestsId;
  END LOOP;
  CLOSE selectLoggedOutGuests;
END